# Generated by Django 4.1.3 on 2023-01-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=32, verbose_name='应用名称')),
                ('type', models.IntegerField(verbose_name='应用类型')),
                ('details', models.CharField(max_length=256, verbose_name='应用描述')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'fater_apps',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('userName', models.CharField(db_column='user_name', max_length=32, verbose_name='用户账号')),
                ('passWord', models.CharField(db_column='pass_word', max_length=32, verbose_name='用户密码')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='用户性别')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('type', models.IntegerField(verbose_name='用户身份')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'fater_users',
            },
        ),
        migrations.CreateModel(
            name='Fingers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('key', models.CharField(max_length=256, verbose_name='关键信息')),
                ('location', models.IntegerField(verbose_name='所在位置')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
                ('app', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to='app.apps')),
            ],
            options={
                'db_table': 'fater_fingers',
            },
        ),
    ]
